name: Linux-CI

on: [push, pull_request]


jobs:

  # The Build and Test Job
  test:
    name: GCC-${{ matrix.compiler-version }} (${{ matrix.build_type }}, Linux)
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-18.04]
        python-version: [3.6]
        compiler-version: [5, 6, 7]
        build_type: [Release, Debug]

    env:
      # Library Variables
      LIBRARY_NAME: xmscore
      XMS_VERSION: 99.99.99
      # Conan Variables
      CONAN_REFERENCE: xmscore/99.99.99
      CONAN_ARCHS: x86_64
      CONAN_USERNAME: aquaveo
      CONAN_CHANNEL: testing
      CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_USER_SECRET }}
      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD_SECRET }}
      CONAN_REMOTES: https://conan.aquaveo.com
      CONAN_BUILD_TYPES: ${{ matrix.build_type }}
      CONAN_GCC_VERSIONS: ${{ matrix.compiler-version }}
      CONAN_DOCKER_IMAGE: docker.aquaveo.com/aquaveo/conan-docker/conan-gcc${{ matrix.compiler-version }}:py36
      # Aquapi Variables
      AQUAPI_USERNAME: ${{ secrets.AQUAPI_USERNAME_SECRET }}
      AQUAPI_PASSWORD: ${{ secrets.AQUAPI_PASSWORD_SECRET }}
      # AQUAPI_URL: ${{ secrets.AQUAPI_URL_SECRET }}
      AQUAPI_URL: https://aquapi.aquaveo.com/aquaveo/dev/+simple
      # Python Variables
      PYTHON_TARGET_VERSION: ${{ matrix.python-version }}
      RELEASE_PYTHON: 'False'


    steps:
      # Checkout Sources
      - uses: actions/checkout@v2
      # Setup Python
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install conan conan_package_tools devpi-client wheel
      # Login to Aquaveo Docker
      - name: Login to Aquaveo Docker
        run: sudo docker login -u ${{ secrets.AQUAVEO_DOCKER_USERNAME_SECRET }} -p ${{ secrets.AQUAVEO_DOCKER_PASSWORD_SECRET }} docker.aquaveo.com
        shell: bash
      # Setup Conan
      - name: Setup Conan Directory
        run: conan user
      # Get Tag Name
      - name: Get Tag
        id: gitTag
        uses: olegtarasov/get-tag@v2
        if: startsWith(github.ref, 'refs/tags/')
      # Set Conan Version
      - name: Set Conan Version
        uses: allenevans/set-env@v1.1.0
        with:
          CONAN_REFERENCE: 'xmscore/${{ steps.gitTag.outputs.tag }}'
          XMS_VERSION: ${{ steps.gitTag.outputs.tag }}
          CONAN_UPLOAD: https://conan.aquaveo.com
          RELEASE_PYTON: 'True'
        if: startsWith(github.ref, 'refs/tags/')
      # Build the Conan Package
      - name: Build the Conan Packages
        run: python build.py
