name: Mac-CI

on: [push, pull_request]


jobs:

  # The Build and Test Job
  test:
    name: Clang-11.0 (${{ matrix.build_type }}, Macos)
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]
        python-version: [3.6]
        build_type: [Release, Debug]

    env:
      # Library Variables
      LIBRARY_NAME: xmscore
      XMS_VERSION: 99.99.99
      # Conan Variables
      CONAN_REFERENCE: xmscore/99.99.99
      CONAN_ARCHS: x86_64
      CONAN_USERNAME: aquaveo
      CONAN_CHANNEL: testing
      CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_USER_SECRET }}
      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD_SECRET }}
      CONAN_REMOTES: https://conan.aquaveo.com
      CONAN_BUILD_TYPES: ${{ matrix.build_type }}
      CONAN_APPLE_CLANG_VERSIONS: '11.0'
      # Aquapi Variables
      AQUAPI_USERNAME: ${{ secrets.AQUAPI_USERNAME_SECRET }}
      AQUAPI_PASSWORD: ${{ secrets.AQUAPI_PASSWORD_SECRET }}
      # AQUAPI_URL: ${{ secrets.AQUAPI_URL_SECRET }}
      AQUAPI_URL: https://aquapi.aquaveo.com/aquaveo/dev/+simple
      # Python Variables
      PYTHON_TARGET_VERSION: ${{ matrix.python-version }}
      RELEASE_PYTHON: 'False'


    steps:
      # Checkout Sources
      - uses: actions/checkout@v2
      # Setup Python
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install conan conan_package_tools devpi-client wheel
      # Setup Xcode
      - uses: sinoru/actions-setup-xcode@v1.1
        with:
          xcode-version: '11.6'
      # Setup Conan
      - name: Setup Conan Directory
        run: conan user
      # Get Tag Name (ONLY RUNS ON TAGS)
      - name: Get Tag
        id: gitTag
        uses: olegtarasov/get-tag@v2
        if: startsWith(github.ref, 'refs/tags/')
      # Set Conan Version (ONLY RUNS ON TAGS)
      - name: Set Conan Version
        uses: allenevans/set-env@v1.1.0
        with:
          CONAN_REFERENCE: 'xmscore/${{ steps.gitTag.outputs.tag }}'
          XMS_VERSION: ${{ steps.gitTag.outputs.tag }}
          CONAN_UPLOAD: https://conan.aquaveo.com
          RELEASE_PYTON: 'True'
        if: startsWith(github.ref, 'refs/tags/')
      # Build the Conan Package
      - name: Build the Conan Packages
        run: python build.py
