name: Windows-CI

on: [push, pull_request]

jobs:

  test:
    name: Visual Studio ${{ matrix.compiler-version }} (${{ matrix.build_type }}, Windows)
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        python-version: [3.6.8]
        compiler-version: [16]
        build_type: [Release, Debug]

    env:
      # Library Variables
      LIBRARY_NAME: xmscore
      XMS_VERSION: 99.99.99
      # Conan Variables
      CONAN_REFERENCE: xmscore/99.99.99
      CONAN_ARCHS: x86_64
      CONAN_USERNAME: aquaveo
      CONAN_CHANNEL: testing
      CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_USER_SECRET }}
      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD_SECRET }}
      CONAN_REMOTES: https://conan.aquaveo.com
      CONAN_BUILD_TYPES: ${{ matrix.build_type }}
      CONAN_VISUAL_VERSIONS: ${{ matrix.compiler-version }}
      # Aquapi Variables
      AQUAPI_USERNAME: ${{ secrets.AQUAPI_USERNAME_SECRET }}
      AQUAPI_PASSWORD: ${{ secrets.AQUAPI_PASSWORD_SECRET }}
      AQUAPI_URL: ${{ secrets.AQUAPI_URL_DEV }}
      # Python Variables
      PYTHON_TARGET_VERSION: ${{ matrix.python-version }}
      RELEASE_PYTHON: 'False'

    steps:
      # Checkout Sources
      - uses: actions/checkout@v2
      # Setup Python
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install conan conan_package_tools devpi-client wheel
      # Setup Visual Studio
      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1.0.1
        with:
          vs-version: ${{ matrix.compiler-version }}
      # Setup Conan
      - name: Setup Conan Directory
        run: conan user
        shell: cmd
      # Get Tag Name
      - name: Get Tag
        id: gitTag
        uses: olegtarasov/get-tag@v2
        if: startsWith(github.ref, 'refs/tags/')
      # Set Conan Version
      - name: Set Conan Version
        uses: allenevans/set-env@v1.1.0
        with:
          CONAN_REFERENCE: 'xmscore/${{ steps.gitTag.outputs.tag }}'
          XMS_VERSION: ${{ steps.gitTag.outputs.tag }}
          CONAN_UPLOAD: https://conan.aquaveo.com
          RELEASE_PYTHON: 'True'
        if: startsWith(github.ref, 'refs/tags/')
      # Check for release branch
      - name: Get Branch Name
        id: gitBranch
        uses: nelonoel/branch-name@v1
      - name: Change Channel and URL if Release Branch
        uses: allenevans/set-env@v1.1.0
        with:
          CONAN_CHANNEL: stable
          AQUAPI_URL: ${{ secrets.AQUAPI_URL_STABLE }}
        if: startsWith(github.ref, 'refs/tags/') && startsWith(env.BRANCH_NAME, 'release-')
      # Build the Conan Package
      - name: Build the Conan Packages
        run: python build.py
        shell: cmd
